Creating Columns

By: Josh Navarro

Goal: Learn how to create columns in Jupyter Notebook using Python Pandas

Data: Created by ChatGPT

In [37]:
# Import that we will use
import pandas as pd
import numpy as np

In [38]:
# Data that we are going to use.
df = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010,
                 1011, 1012, 1013, 1014, 1015],
    "customer_name": ["Maya", "Jordan", "Alex", "Sofia", "Ethan", "Lena", "Chris", "Nora", "Daniel", "Ava",
                      "Marcus", "Isabella", "Noah", "Grace", "Olivia"],
    "product_category": ["Electronics", "Clothing", "Home", "Electronics", "Clothing",
                         "Beauty", "Home", "Electronics", "Beauty", "Clothing",
                         "Home", "Electronics", "Beauty", "Clothing", "Home"],
    "quantity": [2, 5, 1, 3, 4, 2, 6, 1, 3, 2, 5, 4, 1, 7, 2],
    "unit_price": [450, 35, 120, 800, 25, 60, 45, 1100, 40, 75, 90, 300, 85, 20, 150],
    "discount_rate": [0.10, 0.05, 0.00, 0.15, 0.10, 0.00, 0.05, 0.20, 0.10, 0.05,
                      0.00, 0.10, 0.00, 0.05, 0.15],
    "shipping_cost": [20, 8, 15, 25, 7, 10, 18, 30, 9, 12, 16, 22, 8, 10, 20],
    "order_date": pd.to_datetime([
        "2026-01-05", "2026-01-08", "2026-01-12", "2026-01-15", "2026-01-20",
        "2026-02-02", "2026-02-10", "2026-02-14", "2026-02-18", "2026-03-01",
        "2026-03-05", "2026-03-12", "2026-03-18", "2026-03-22", "2026-03-30"
    ])
})

df

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08
2,1003,Alex,Home,1,120,0.00,15,2026-01-12
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20
5,1006,Lena,Beauty,2,60,0.00,10,2026-02-02
6,1007,Chris,Home,6,45,0.05,18,2026-02-10
7,1008,Nora,Electronics,1,1100,0.20,30,2026-02-14
8,1009,Daniel,Beauty,3,40,0.10,9,2026-02-18
9,1010,Ava,Clothing,2,75,0.05,12,2026-03-01
10,1011,Marcus,Home,5,90,0.00,16,2026-03-05
11,1012,Isabella,Electronics,4,300,0.10,22,2026-03-12
12,1013,Noah,Beauty,1,85,0.00,8,2026-03-18
13,1014,Grace,Clothing,7,20,0.05,10,2026-03-22
14,1015,Olivia,Home,2,150,0.15,20,2026-03-30

Creating Columns

In [39]:
# Copying the dataframe into another dataframe
column_df = df.copy()
# Check the cols dataframe
column_df.columns

Index(['order_id', 'customer_name', 'product_category', 'quantity',
       'unit_price', 'discount_rate', 'shipping_cost', 'order_date'],
      dtype='object')

1 Direct Column Assignment

The direct column is the most direct way to create a column in the dataframe, this is done by defining a new column name, then equaling it to a value or a calcualtion

In [40]:
# Create a column that uses that qunitity and the unit_price
column_df['total_price'] = column_df['quantity'] * column_df['unit_price']
# Check the dataframe
column_df.head()

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date,total_price
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05,900
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08,175
2,1003,Alex,Home,1,120,0.00,15,2026-01-12,120
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15,2400
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20,100

2 Creating Columns with .assign()

To create a column you can also use the function .assign(). Which the fucntion you need to pass the column name equal to the value or calculations.

In [41]:
column_df.assign(
    price_after_discount = column_df['unit_price'] * (1 - column_df['discount_rate'])
)

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date,total_price,price_after_discount
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05,900,405.00
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08,175,33.25
2,1003,Alex,Home,1,120,0.00,15,2026-01-12,120,120.00
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15,2400,680.00
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20,100,22.50
5,1006,Lena,Beauty,2,60,0.00,10,2026-02-02,120,60.00
6,1007,Chris,Home,6,45,0.05,18,2026-02-10,270,42.75
7,1008,Nora,Electronics,1,1100,0.20,30,2026-02-14,1100,880.00
8,1009,Daniel,Beauty,3,40,0.10,9,2026-02-18,120,36.00
9,1010,Ava,Clothing,2,75,0.05,12,2026-03-01,150,71.25
10,1011,Marcus,Home,5,90,0.00,16,2026-03-05,450,90.00
11,1012,Isabella,Electronics,4,300,0.10,22,2026-03-12,1200,270.00
12,1013,Noah,Beauty,1,85,0.00,8,2026-03-18,85,85.00
13,1014,Grace,Clothing,7,20,0.05,10,2026-03-22,140,19.00
14,1015,Olivia,Home,2,150,0.15,20,2026-03-30,300,127.50

3 Creating Columns with .loc[]

Creating columns using the .loc90 function you need to use a condition to create the column. To do this you start off with column that has a default value and then use .loc to update those values.

In [42]:
# Create the default value
column_df["bulk_order"] = "No"
# Update those values using .loc[]
column_df.loc[column_df["quantity"] >= 5, "bulk_order"] = "Yes"

column_df.head()

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date,total_price,bulk_order
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05,900,No
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08,175,Yes
2,1003,Alex,Home,1,120,0.00,15,2026-01-12,120,No
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15,2400,No
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20,100,No

4 Creating Columns with np.where()

Using the np.where() is useful for creating the column if there are two possible outcomes. Which the function takes in three columns, the condition, the value if true, and then the value if not true

In [43]:
# Create a column to see if the discounts were used
column_df["discount_used"] = np.where(
    column_df["discount_rate"] > 0,
    "Yes",
    "No"
)

# Check the dataframe 
column_df.head()

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date,total_price,bulk_order,discount_used
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05,900,No,Yes
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08,175,Yes,Yes
2,1003,Alex,Home,1,120,0.00,15,2026-01-12,120,No,No
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15,2400,No,Yes
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20,100,No,Yes

5 Creating columns with np.select()

Using the np.select() is used when you have to use multiple conditions. The function itself will pass the arguments of the conditions being a list, choices being a list, and then third is a default being "Other'

In [44]:
# Create the conditions 
conditions = [
    column_df["unit_price"] < 50,
    column_df["unit_price"].between(50, 300),
    column_df["unit_price"] > 300
]
# Create the choices
choices = [
    "Low Price",
    "Medium Price",
    "High Price"
]

# Use the np.select.
column_df["price_level"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

# Check the dataframe
column_df.head()

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date,total_price,bulk_order,discount_used,price_level
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05,900,No,Yes,High Price
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08,175,Yes,Yes,Low Price
2,1003,Alex,Home,1,120,0.00,15,2026-01-12,120,No,No,Medium Price
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15,2400,No,Yes,High Price
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20,100,No,Yes,Low Price

6 Creating columns with .map()

The function .map() is able to create a new column by matching the values from a dictionary. This is done by having or creating a dictionary that matches values together.

In [45]:
# Create the map that matches the categories
category_map = {
    "Electronics": "Technology",
    "Clothing": "Fashion",
    "Home": "Household",
    "Beauty": "Personal Care"
}

# Use the .map() to create a new column
column_df["category_group"] = column_df["product_category"].map(category_map)

# Check the dataframe
column_df.head()

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date,total_price,bulk_order,discount_used,price_level,category_group
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05,900,No,Yes,High Price,Technology
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08,175,Yes,Yes,Low Price,Fashion
2,1003,Alex,Home,1,120,0.00,15,2026-01-12,120,No,No,Medium Price,Household
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15,2400,No,Yes,High Price,Technology
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20,100,No,Yes,Low Price,Fashion

7 Creating Columns with .apply()

The .apply() function allows you to createa  column using a customm function. So this works by defining a function and then passing that fucntion into .apply().

In [46]:
# Create a function that is able to classify the shipping
def classify_shipping(cost):
    if cost >= 20:
        return "High Shipping"
    else:
        return "Normal Shipping"

# Use .apply() to apply the function to the column
column_df['shipping_level'] = column_df["shipping_cost"].apply(classify_shipping)

# Check the dataframe
column_df.head()

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date,total_price,bulk_order,discount_used,price_level,category_group,shipping_level
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05,900,No,Yes,High Price,Technology,High Shipping
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08,175,Yes,Yes,Low Price,Fashion,Normal Shipping
2,1003,Alex,Home,1,120,0.00,15,2026-01-12,120,No,No,Medium Price,Household,Normal Shipping
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15,2400,No,Yes,High Price,Technology,High Shipping
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20,100,No,Yes,Low Price,Fashion,Normal Shipping

8  Creating Columns from Text with .str

The .str allows you to create a column from text data. This is done by using the column with text data, and then using .str with with antoher function such as .method(), upper(), and etc.

In [47]:
# Find the customer initial
column_df["customer_initial"] = column_df["customer_name"].str[0]

# Check the data frame
column_df.head()

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date,total_price,bulk_order,discount_used,price_level,category_group,shipping_level,customer_initial
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05,900,No,Yes,High Price,Technology,High Shipping,M
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08,175,Yes,Yes,Low Price,Fashion,Normal Shipping,J
2,1003,Alex,Home,1,120,0.00,15,2026-01-12,120,No,No,Medium Price,Household,Normal Shipping,A
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15,2400,No,Yes,High Price,Technology,High Shipping,S
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20,100,No,Yes,Low Price,Fashion,Normal Shipping,E

9 Creating Columns from Date with .dt

The .dt accessor allows you to create a new column using a date time column. This is done by using the .dt accessor with another date time function such as date_part, year, and etc.

In [48]:
# Find the order_year
column_df["order_year"] = column_df["order_date"].dt.year
# Check the dataframe
column_df.head()

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date,total_price,bulk_order,discount_used,price_level,category_group,shipping_level,customer_initial,order_year
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05,900,No,Yes,High Price,Technology,High Shipping,M,2026
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08,175,Yes,Yes,Low Price,Fashion,Normal Shipping,J,2026
2,1003,Alex,Home,1,120,0.00,15,2026-01-12,120,No,No,Medium Price,Household,Normal Shipping,A,2026
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15,2400,No,Yes,High Price,Technology,High Shipping,S,2026
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20,100,No,Yes,Low Price,Fashion,Normal Shipping,E,2026

11 Creating Boolean Columns 

To create boolean columns you can use the direct column creation but just use a condition

In [49]:
# Create a column that checks whether there is a discount
column_df["has_discount"] = column_df["discount_rate"] > 0

# Check the dataframe
column_df.head()

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date,total_price,bulk_order,discount_used,price_level,category_group,shipping_level,customer_initial,order_year,has_discount
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05,900,No,Yes,High Price,Technology,High Shipping,M,2026,True
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08,175,Yes,Yes,Low Price,Fashion,Normal Shipping,J,2026,True
2,1003,Alex,Home,1,120,0.00,15,2026-01-12,120,No,No,Medium Price,Household,Normal Shipping,A,2026,False
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15,2400,No,Yes,High Price,Technology,High Shipping,S,2026,True
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20,100,No,Yes,Low Price,Fashion,Normal Shipping,E,2026,True

12 Creating Columns with .astype()

You can also create a new column by defining a type for a previous column. Which this is done by using the .astype() function.

In [50]:
# For the order_id, create a new column with the type string
column_df["order_id_text"] = column_df["order_id"].astype(str)

# Check the dataframe
column_df.head()

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date,total_price,bulk_order,discount_used,price_level,category_group,shipping_level,customer_initial,order_year,has_discount,order_id_text
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05,900,No,Yes,High Price,Technology,High Shipping,M,2026,True,1001
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08,175,Yes,Yes,Low Price,Fashion,Normal Shipping,J,2026,True,1002
2,1003,Alex,Home,1,120,0.00,15,2026-01-12,120,No,No,Medium Price,Household,Normal Shipping,A,2026,False,1003
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15,2400,No,Yes,High Price,Technology,High Shipping,S,2026,True,1004
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20,100,No,Yes,Low Price,Fashion,Normal Shipping,E,2026,True,1005

13 Creating Columns with .round()

Creating a column with the .round() function this is done by using the direct column, but adding the .round() rounds that value.

In [51]:
# Create the column the shipping per item column but use the rounded function 
column_df["shipping_per_item_rounded"] = (
    column_df["shipping_cost"] / column_df["quantity"]
).round(2)

# Check the dataframe
column_df.head()

,order_id,customer_name,product_category,quantity,unit_price,discount_rate,shipping_cost,order_date,total_price,bulk_order,discount_used,price_level,category_group,shipping_level,customer_initial,order_year,has_discount,order_id_text,shipping_per_item_rounded
0,1001,Maya,Electronics,2,450,0.10,20,2026-01-05,900,No,Yes,High Price,Technology,High Shipping,M,2026,True,1001,10.00
1,1002,Jordan,Clothing,5,35,0.05,8,2026-01-08,175,Yes,Yes,Low Price,Fashion,Normal Shipping,J,2026,True,1002,1.60
2,1003,Alex,Home,1,120,0.00,15,2026-01-12,120,No,No,Medium Price,Household,Normal Shipping,A,2026,False,1003,15.00
3,1004,Sofia,Electronics,3,800,0.15,25,2026-01-15,2400,No,Yes,High Price,Technology,High Shipping,S,2026,True,1004,8.33
4,1005,Ethan,Clothing,4,25,0.10,7,2026-01-20,100,No,Yes,Low Price,Fashion,Normal Shipping,E,2026,True,1005,1.75