Date Transformations

By: Josh Navarro

Goal: Learn how to do Date Transformation in Jupyter Notebook, using Python Pandas

Data: Created by ChatGPT

In [36]:
# Imports that I will be using
import pandas as pd
import numpy as np

In [37]:
# Create the data
df = pd.DataFrame({
    "record_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                  11, 12, 13, 14, 15, 16],

    "event_name": ["Signup", "Purchase", "Support Ticket", "Delivery", 
                   "Subscription Start", "Login", "Payment", "Appointment",
                   "Trial Start", "Renewal", "Cancellation", "Webinar",
                   "Return Request", "Survey", "Account Update", "Follow Up"],

    "event_date": ["2026-01-05", "2026-01-12", "2026-01-20", "2026-02-03",
                   "2026-02-14", "2026-02-28", "2026-03-04", "2026-03-18",
                   "2026-03-25", "2026-04-01", "2026-04-09", "2026-04-15",
                   "2026-04-22", "2026-05-02", "2026-05-11", "2026-05-20"],

    "start_date": ["2026-01-01", "2026-01-10", "2026-01-18", "2026-02-01",
                   "2026-02-10", "2026-02-25", "2026-03-01", "2026-03-15",
                   "2026-03-20", "2026-03-28", "2026-04-05", "2026-04-10",
                   "2026-04-18", "2026-04-30", "2026-05-08", "2026-05-15"],

    "end_date": ["2026-01-07", "2026-01-14", "2026-01-24", "2026-02-06",
                 "2026-02-20", "2026-03-02", "2026-03-08", "2026-03-20",
                 "2026-03-30", "2026-04-05", "2026-04-12", "2026-04-18",
                 "2026-04-27", "2026-05-05", "2026-05-15", "2026-05-25"],

    "last_active_date": ["2026-01-06", "2026-01-13", "2026-01-22", "2026-02-04",
                         "2026-02-18", "2026-03-01", "2026-03-06", "2026-03-19",
                         "2026-03-28", "2026-04-04", "2026-04-10", "2026-04-17",
                         "2026-04-24", "2026-05-04", "2026-05-14", "2026-05-23"],

    "reminder_date": ["2026-01-04", "2026-01-11", "2026-01-19", "2026-02-02",
                      "2026-02-13", "2026-02-27", "2026-03-03", "2026-03-17",
                      "2026-03-24", "2026-03-31", "2026-04-08", "2026-04-14",
                      "2026-04-21", "2026-05-01", "2026-05-10", "2026-05-19"]
})


df

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13
5,6,Login,2026-02-28,2026-02-25,2026-03-02,2026-03-01,2026-02-27
6,7,Payment,2026-03-04,2026-03-01,2026-03-08,2026-03-06,2026-03-03
7,8,Appointment,2026-03-18,2026-03-15,2026-03-20,2026-03-19,2026-03-17
8,9,Trial Start,2026-03-25,2026-03-20,2026-03-30,2026-03-28,2026-03-24
9,10,Renewal,2026-04-01,2026-03-28,2026-04-05,2026-04-04,2026-03-31
10,11,Cancellation,2026-04-09,2026-04-05,2026-04-12,2026-04-10,2026-04-08
11,12,Webinar,2026-04-15,2026-04-10,2026-04-18,2026-04-17,2026-04-14
12,13,Return Request,2026-04-22,2026-04-18,2026-04-27,2026-04-24,2026-04-21
13,14,Survey,2026-05-02,2026-04-30,2026-05-05,2026-05-04,2026-05-01
14,15,Account Update,2026-05-11,2026-05-08,2026-05-15,2026-05-14,2026-05-10
15,16,Follow Up,2026-05-20,2026-05-15,2026-05-25,2026-05-23,2026-05-19

Date Transformations

In [38]:
# Copy the data
date_df = df.copy()
# Check the data
date_df.columns

Index(['record_id', 'event_name', 'event_date', 'start_date', 'end_date',
       'last_active_date', 'reminder_date'],
      dtype='object')

1 Convert text dates using the pd.to_datetime()

At the start of the date transformations you have to change the date column using the pd.to_datetime()

In [39]:
# Convert that date column into a datetime

# Create a list of the columns
date_columns = ["event_date", "start_date", "end_date", "last_active_date", "reminder_date"]
# Convert all of those columns into datetime
for col in date_columns:
    date_df[col] = pd.to_datetime(date_df[col])
# Check the data types
date_df.dtypes

record_id                    int64
event_name                  object
event_date          datetime64[ns]
start_date          datetime64[ns]
end_date            datetime64[ns]
last_active_date    datetime64[ns]
reminder_date       datetime64[ns]
dtype: object

2 Extract the year

You can extract the year from a column by using .dt.year

In [40]:
# Extract the year from the ever_date column
date_df['Event_Year'] = date_df['event_date'].dt.year
# Check the data frame
date_df[['record_id', 'event_name', 'Event_Year']]

    record_id          event_name  Event_Year
0           1              Signup        2026
1           2            Purchase        2026
2           3      Support Ticket        2026
3           4            Delivery        2026
4           5  Subscription Start        2026
5           6               Login        2026
6           7             Payment        2026
7           8         Appointment        2026
8           9         Trial Start        2026
9          10             Renewal        2026
10         11        Cancellation        2026
11         12             Webinar        2026
12         13      Return Request        2026
13         14              Survey        2026
14         15      Account Update        2026
15         16           Follow Up        2026

3 Extract the month number

To extract the month number you can use the function of .dt.month

In [41]:
# Extract the month out of the event_month column
date_df["event_month"] = date_df["event_date"].dt.month
# Check the data frame
date_df.head()

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04,2026,1
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11,2026,1
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19,2026,1
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02,2026,2
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13,2026,2

4 Extract the month name 

In order to extract the month name you need to use the funciton of .dt.month_name()

In [42]:
# Extract the month name out of the event_date column
date_df["event_month_name"] = date_df["event_date"].dt.month_name()
# Check the dataframe
date_df.head()

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month,event_month_name
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04,2026,1,January
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11,2026,1,January
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19,2026,1,January
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02,2026,2,February
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13,2026,2,February

5 Extract the day of the week

To extract the day of the week you need to use the .dt.day

In [43]:
# Extract the day from the event_date column
date_df['event_weekday'] = date_df['event_date'].dt.day
# Check the dataframe
date_df.head()

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month,event_month_name,event_weekday
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04,2026,1,January,5
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11,2026,1,January,12
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19,2026,1,January,20
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02,2026,2,February,3
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13,2026,2,February,14

6 Extract the quarter

The quarter refers to the range of month, Jan-Mar being Q1 and so on to find this you can use the .dt.quarter

In [44]:
# Extract the quarter from the event_date column
date_df['event_quarter'] = date_df['event_date'].dt.quarter
# Check the dataframe
date_df.head()

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month,event_month_name,event_weekday,event_quarter
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04,2026,1,January,5,1
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11,2026,1,January,12,1
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19,2026,1,January,20,1
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02,2026,2,February,3,1
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13,2026,2,February,14,1

7 Create Year-Month Periods

To create the year month periods you have to use the function of pd.to_period(), which this could be useful when you are trying to do the monthly trend analysis.

In [45]:
# Find the monthly period for the event_date
date_df["event_year_month"] = date_df["event_date"].dt.to_period("M")
# Check the datafrmae
date_df.head()

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month,event_month_name,event_weekday,event_quarter,event_year_month
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04,2026,1,January,5,1,2026-01
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11,2026,1,January,12,1,2026-01
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19,2026,1,January,20,1,2026-01
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02,2026,2,February,3,1,2026-02
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13,2026,2,February,14,1,2026-02

8 Calculate the difference between dates

To calculate the difference between the dates you can use the minus from the end of the date till the start of it.

In [46]:
# Find the difference betwene the end_date and the start_date
date_df["duration_days"] = (date_df["end_date"] - date_df["start_date"]).dt.days
# Check the dataframe
date_df.head()

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month,event_month_name,event_weekday,event_quarter,event_year_month,duration_days
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04,2026,1,January,5,1,2026-01,6
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11,2026,1,January,12,1,2026-01,4
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19,2026,1,January,20,1,2026-01,6
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02,2026,2,February,3,1,2026-02,5
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13,2026,2,February,14,1,2026-02,10

9 Calculate days since last activity

To calculate the days since last activity you can use the difference between the date of "today" and the when last active.

In [47]:
# Create the "today"
today = pd.to_datetime("2026-06-01")
# Find the difference
date_df["days_since_last_active"] = (
    today - date_df["last_active_date"]
).dt.days
# Check the dataframe
date_df.head()

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month,event_month_name,event_weekday,event_quarter,event_year_month,duration_days,days_since_last_active
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04,2026,1,January,5,1,2026-01,6,146
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11,2026,1,January,12,1,2026-01,4,139
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19,2026,1,January,20,1,2026-01,6,130
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02,2026,2,February,3,1,2026-02,5,117
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13,2026,2,February,14,1,2026-02,10,103

10 Calculate days until reminder

This is done by also using the today and then subtracting it from a reminder date

In [48]:
# Create the "today"
today = pd.to_datetime("2026-06-01")
# Find the days until the reminder
date_df["days_until_reminder"] = (
    date_df["reminder_date"] - today
).dt.days
# Check the dataframe
date_df.head()

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month,event_month_name,event_weekday,event_quarter,event_year_month,duration_days,days_since_last_active,days_until_reminder
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04,2026,1,January,5,1,2026-01,6,146,-148
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11,2026,1,January,12,1,2026-01,4,139,-141
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19,2026,1,January,20,1,2026-01,6,130,-133
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02,2026,2,February,3,1,2026-02,5,117,-119
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13,2026,2,February,14,1,2026-02,10,103,-108

11 Create a past/future label

This is done by also using a today, and then using a condition to decide whether that date has already past or will be in the future

In [49]:
# Create the today
today = pd.to_datetime("2026-06-01")
# Find whether that date will past or future
date_df["reminder_status"] = np.where(
    date_df["reminder_date"] < today,
    "Past Reminder",
    "Upcoming Reminder"
)
# Check the dataframe
date_df.head()

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month,event_month_name,event_weekday,event_quarter,event_year_month,duration_days,days_since_last_active,days_until_reminder,reminder_status
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04,2026,1,January,5,1,2026-01,6,146,-148,Past Reminder
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11,2026,1,January,12,1,2026-01,4,139,-141,Past Reminder
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19,2026,1,January,20,1,2026-01,6,130,-133,Past Reminder
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02,2026,2,February,3,1,2026-02,5,117,-119,Past Reminder
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13,2026,2,February,14,1,2026-02,10,103,-108,Past Reminder

12 Create a duration category

To create this duration category, start with conditions that will decide whether that duration will be short, medium, or long, and then using that create the column using np.select()

In [50]:
# Create the conditions
conditions = [
    date_df["duration_days"] <= 5,
    date_df["duration_days"].between(6, 9),
    date_df["duration_days"] >= 10
]
# Create the categories
choices = ["Short", "Medium", "Long"]
# Create the new column
date_df["duration_category"] = np.select(
    conditions,
    choices,
    default="Unknown"
)
# Check the data frame
date_df.head()

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month,event_month_name,event_weekday,event_quarter,event_year_month,duration_days,days_since_last_active,days_until_reminder,reminder_status,duration_category
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04,2026,1,January,5,1,2026-01,6,146,-148,Past Reminder,Medium
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11,2026,1,January,12,1,2026-01,4,139,-141,Past Reminder,Short
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19,2026,1,January,20,1,2026-01,6,130,-133,Past Reminder,Medium
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02,2026,2,February,3,1,2026-02,5,117,-119,Past Reminder,Short
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13,2026,2,February,14,1,2026-02,10,103,-108,Past Reminder,Long

13 Sort by Date

You can sort by the date by using the function .sort_values()

In [51]:
# Sort the dataframe by the event_date
date_df.sort_values('event_date')

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month,event_month_name,event_weekday,event_quarter,event_year_month,duration_days,days_since_last_active,days_until_reminder,reminder_status,duration_category
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04,2026,1,January,5,1,2026-01,6,146,-148,Past Reminder,Medium
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11,2026,1,January,12,1,2026-01,4,139,-141,Past Reminder,Short
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19,2026,1,January,20,1,2026-01,6,130,-133,Past Reminder,Medium
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02,2026,2,February,3,1,2026-02,5,117,-119,Past Reminder,Short
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13,2026,2,February,14,1,2026-02,10,103,-108,Past Reminder,Long
5,6,Login,2026-02-28,2026-02-25,2026-03-02,2026-03-01,2026-02-27,2026,2,February,28,1,2026-02,5,92,-94,Past Reminder,Short
6,7,Payment,2026-03-04,2026-03-01,2026-03-08,2026-03-06,2026-03-03,2026,3,March,4,1,2026-03,7,87,-90,Past Reminder,Medium
7,8,Appointment,2026-03-18,2026-03-15,2026-03-20,2026-03-19,2026-03-17,2026,3,March,18,1,2026-03,5,74,-76,Past Reminder,Short
8,9,Trial Start,2026-03-25,2026-03-20,2026-03-30,2026-03-28,2026-03-24,2026,3,March,25,1,2026-03,10,65,-69,Past Reminder,Long
9,10,Renewal,2026-04-01,2026-03-28,2026-04-05,2026-04-04,2026-03-31,2026,4,April,1,2,2026-04,8,58,-62,Past Reminder,Medium
10,11,Cancellation,2026-04-09,2026-04-05,2026-04-12,2026-04-10,2026-04-08,2026,4,April,9,2,2026-04,7,52,-54,Past Reminder,Medium
11,12,Webinar,2026-04-15,2026-04-10,2026-04-18,2026-04-17,2026-04-14,2026,4,April,15,2,2026-04,8,45,-48,Past Reminder,Medium
12,13,Return Request,2026-04-22,2026-04-18,2026-04-27,2026-04-24,2026-04-21,2026,4,April,22,2,2026-04,9,38,-41,Past Reminder,Medium
13,14,Survey,2026-05-02,2026-04-30,2026-05-05,2026-05-04,2026-05-01,2026,5,May,2,2,2026-05,5,28,-31,Past Reminder,Short
14,15,Account Update,2026-05-11,2026-05-08,2026-05-15,2026-05-14,2026-05-10,2026,5,May,11,2,2026-05,7,18,-22,Past Reminder,Medium
15,16,Follow Up,2026-05-20,2026-05-15,2026-05-25,2026-05-23,2026-05-19,2026,5,May,20,2,2026-05,10,9,-13,Past Reminder,Long

14 Filter by date

You can use filtering methods on date columns if they have the type of date time. This could be done by boolean masking or just .filter()

In [52]:
# Find the event_dates that are more than 2026-03-01
date_df[date_df["event_date"] >= "2026-03-01"]

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month,event_month_name,event_weekday,event_quarter,event_year_month,duration_days,days_since_last_active,days_until_reminder,reminder_status,duration_category
6,7,Payment,2026-03-04,2026-03-01,2026-03-08,2026-03-06,2026-03-03,2026,3,March,4,1,2026-03,7,87,-90,Past Reminder,Medium
7,8,Appointment,2026-03-18,2026-03-15,2026-03-20,2026-03-19,2026-03-17,2026,3,March,18,1,2026-03,5,74,-76,Past Reminder,Short
8,9,Trial Start,2026-03-25,2026-03-20,2026-03-30,2026-03-28,2026-03-24,2026,3,March,25,1,2026-03,10,65,-69,Past Reminder,Long
9,10,Renewal,2026-04-01,2026-03-28,2026-04-05,2026-04-04,2026-03-31,2026,4,April,1,2,2026-04,8,58,-62,Past Reminder,Medium
10,11,Cancellation,2026-04-09,2026-04-05,2026-04-12,2026-04-10,2026-04-08,2026,4,April,9,2,2026-04,7,52,-54,Past Reminder,Medium
11,12,Webinar,2026-04-15,2026-04-10,2026-04-18,2026-04-17,2026-04-14,2026,4,April,15,2,2026-04,8,45,-48,Past Reminder,Medium
12,13,Return Request,2026-04-22,2026-04-18,2026-04-27,2026-04-24,2026-04-21,2026,4,April,22,2,2026-04,9,38,-41,Past Reminder,Medium
13,14,Survey,2026-05-02,2026-04-30,2026-05-05,2026-05-04,2026-05-01,2026,5,May,2,2,2026-05,5,28,-31,Past Reminder,Short
14,15,Account Update,2026-05-11,2026-05-08,2026-05-15,2026-05-14,2026-05-10,2026,5,May,11,2,2026-05,7,18,-22,Past Reminder,Medium
15,16,Follow Up,2026-05-20,2026-05-15,2026-05-25,2026-05-23,2026-05-19,2026,5,May,20,2,2026-05,10,9,-13,Past Reminder,Long

15 Format dates as strings

You can format the dates as strings, by using the .dt.strftime() and then passing the arugment of a specific formatting.

In [53]:
# Format the event date column
date_df["formatted_event_date"] = date_df["event_date"].dt.strftime("%m/%d/%Y")
# Check the data frame
date_df.head()

,record_id,event_name,event_date,start_date,end_date,last_active_date,reminder_date,Event_Year,event_month,event_month_name,event_weekday,event_quarter,event_year_month,duration_days,days_since_last_active,days_until_reminder,reminder_status,duration_category,formatted_event_date
0,1,Signup,2026-01-05,2026-01-01,2026-01-07,2026-01-06,2026-01-04,2026,1,January,5,1,2026-01,6,146,-148,Past Reminder,Medium,01/05/2026
1,2,Purchase,2026-01-12,2026-01-10,2026-01-14,2026-01-13,2026-01-11,2026,1,January,12,1,2026-01,4,139,-141,Past Reminder,Short,01/12/2026
2,3,Support Ticket,2026-01-20,2026-01-18,2026-01-24,2026-01-22,2026-01-19,2026,1,January,20,1,2026-01,6,130,-133,Past Reminder,Medium,01/20/2026
3,4,Delivery,2026-02-03,2026-02-01,2026-02-06,2026-02-04,2026-02-02,2026,2,February,3,1,2026-02,5,117,-119,Past Reminder,Short,02/03/2026
4,5,Subscription Start,2026-02-14,2026-02-10,2026-02-20,2026-02-18,2026-02-13,2026,2,February,14,1,2026-02,10,103,-108,Past Reminder,Long,02/14/2026