Merging and Joining

By: Josh Navarro

Goal: Learn how to Merge and Join, in Jupyter Notebook, using Python Pandas.

Data: ChatGPT

In [21]:
# Imports that we are going to be using
import pandas as pd

In [22]:
# Create the dataframes
customers_df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "customer_name": ["Maya Chen", "Jordan Smith", "Alex Rivera", "Sofia Garcia",
                      "Ethan Brown", "Lena Patel", "Chris Johnson", "Nora Lee"],
    "city": ["Los Angeles", "San Diego", "Phoenix", "Los Angeles",
             "Las Vegas", "San Francisco", "Seattle", "Portland"],
    "membership_level": ["Gold", "Silver", "Bronze", "Gold",
                         "Silver", "Platinum", "Bronze", "Gold"]
})

orders_df = pd.DataFrame({
    "order_id": [5001, 5002, 5003, 5004, 5005, 5006, 5007, 5008, 5009, 5010],
    "customer_id": [101, 102, 101, 104, 109, 103, 106, 102, 110, 108],
    "product_id": [201, 202, 203, 201, 204, 205, 202, 206, 201, 207],
    "order_date": pd.to_datetime(["2026-01-05", "2026-01-07", "2026-01-12",
                                  "2026-01-15", "2026-01-18", "2026-01-20",
                                  "2026-01-22", "2026-01-25", "2026-01-27",
                                  "2026-01-30"]),
    "quantity": [2, 1, 3, 1, 4, 2, 1, 5, 2, 1]
})

products_df = pd.DataFrame({
    "product_id": [201, 202, 203, 204, 205, 206],
    "product_name": ["Laptop Stand", "Wireless Mouse", "Keyboard",
                     "Monitor", "USB-C Hub", "Desk Lamp"],
    "category": ["Office", "Electronics", "Electronics",
                 "Electronics", "Accessories", "Office"],
    "unit_price": [45, 25, 70, 180, 35, 40]
})

shipping_df = pd.DataFrame({
    "order_id": [5001, 5002, 5003, 5004, 5006, 5007, 5008],
    "shipping_status": ["Delivered", "Shipped", "Delivered", "Processing",
                        "Delivered", "Cancelled", "Shipped"],
    "shipping_cost": [8, 6, 10, 7, 9, 0, 12]
})

Merging and Joining

Merging and Joining are similar in the fact that they both merge/join together columns. The main difference is that merge will merge the dataframe together based on common columns, while the join will join based on the indices.

1 Basic Merge with pd.merge()

The basic merge will be done with pd.merge() and taking the arguements, of the left df, right df, and then on = "Column".

In [23]:
# Merge on the orders data frame 
# and then customers data frame using the customer_id

order_customers = pd.merge(
    orders_df,
    customers_df,
    on = "customer_id"
)

order_customers.head()

,order_id,customer_id,product_id,order_date,quantity,customer_name,city,membership_level
0,5001,101,201,2026-01-05,2,Maya Chen,Los Angeles,Gold
1,5002,102,202,2026-01-07,1,Jordan Smith,San Diego,Silver
2,5003,101,203,2026-01-12,3,Maya Chen,Los Angeles,Gold
3,5004,104,201,2026-01-15,1,Sofia Garcia,Los Angeles,Gold
4,5006,103,205,2026-01-20,2,Alex Rivera,Phoenix,Bronze

2 Inner Join

Inner join refers to keeping only matching rows. By default the pd.merge will use this method for the merging. But to define it you add on the how = "inner"

In [24]:
# Using the order_df, customers_df, 
# and then customer_id column use an inner join 
inner_join = pd.merge(
    orders_df,
    customers_df,
    on = "customer_id",
    how = "inner"
)
# Check the dataframe
inner_join.head()

,order_id,customer_id,product_id,order_date,quantity,customer_name,city,membership_level
0,5001,101,201,2026-01-05,2,Maya Chen,Los Angeles,Gold
1,5002,102,202,2026-01-07,1,Jordan Smith,San Diego,Silver
2,5003,101,203,2026-01-12,3,Maya Chen,Los Angeles,Gold
3,5004,104,201,2026-01-15,1,Sofia Garcia,Los Angeles,Gold
4,5006,103,205,2026-01-20,2,Alex Rivera,Phoenix,Bronze

3 Left Join

The left join will keep all the rows in the left dataframe, and then adds the matching data from the dataframe. This is done by using the pd.merge() and then having the argument how = "left"

In [25]:
# Use the orders_df, customers_df, and the customer_id, 
# do a left join
left_join = pd.merge(
    orders_df,
    customers_df,
    on = "customer_id",
    how = "left"
)
# Check the dataframe
left_join.head()

,order_id,customer_id,product_id,order_date,quantity,customer_name,city,membership_level
0,5001,101,201,2026-01-05,2,Maya Chen,Los Angeles,Gold
1,5002,102,202,2026-01-07,1,Jordan Smith,San Diego,Silver
2,5003,101,203,2026-01-12,3,Maya Chen,Los Angeles,Gold
3,5004,104,201,2026-01-15,1,Sofia Garcia,Los Angeles,Gold
4,5005,109,204,2026-01-18,4,NaN,NaN,NaN

4 Right Join

The right join will keep all the rows from the right dataframe and then adds the matching data from the left Dataframe. This is done by using the pd.merge() and using the argument of how = "right"

In [26]:
# Use the order_df, and customer_df, on the customer_id 
# Do a right join
right_join = pd.merge(
    orders_df,
    customers_df,
    on = "customer_id",
    how = "right"
)
# Check the dataframe
right_join.head()

,order_id,customer_id,product_id,order_date,quantity,customer_name,city,membership_level
0,5001.0,101,201.0,2026-01-05,2.0,Maya Chen,Los Angeles,Gold
1,5003.0,101,203.0,2026-01-12,3.0,Maya Chen,Los Angeles,Gold
2,5002.0,102,202.0,2026-01-07,1.0,Jordan Smith,San Diego,Silver
3,5008.0,102,206.0,2026-01-25,5.0,Jordan Smith,San Diego,Silver
4,5006.0,103,205.0,2026-01-20,2.0,Alex Rivera,Phoenix,Bronze

5 Outer Join

The outer join will keep all the rows from the both of the dataframes. This is done by using the pd.merge() and then the argument how = "outer"

In [27]:
# Use the orders_df, customers_df, on the customer_id column
# Create a outer_join
outer_join = pd.merge(
    orders_df,
    customers_df,
    on="customer_id",
    how="outer"
)

# Check the dataframe
outer_join.head()

,order_id,customer_id,product_id,order_date,quantity,customer_name,city,membership_level
0,5001.0,101,201.0,2026-01-05,2.0,Maya Chen,Los Angeles,Gold
1,5003.0,101,203.0,2026-01-12,3.0,Maya Chen,Los Angeles,Gold
2,5002.0,102,202.0,2026-01-07,1.0,Jordan Smith,San Diego,Silver
3,5008.0,102,206.0,2026-01-25,5.0,Jordan Smith,San Diego,Silver
4,5006.0,103,205.0,2026-01-20,2.0,Alex Rivera,Phoenix,Bronze

6 Merge on different column names

There are cases when the key columns have different names. If this is the case you can choose the column to use for each dataframe by add the argument left_on = "column", and right_on = "right_key.

In [28]:
# Create another dataframe for this example
customer_regions_df = pd.DataFrame({
    "cust_id": [101, 102, 103, 104, 105, 106],
    "region": ["West", "West", "Southwest", "West", "Southwest", "West"]
})

# use merge on the customers_df and then the customer_regions_df,
# for the left use customer_id, and then right use the cust_id. 
# Use left join
customers_regions = pd.merge(
    customers_df,
    customer_regions_df,
    left_on="customer_id",
    right_on="cust_id",
    how="left"
)

# Check the dataframe
customers_regions

,customer_id,customer_name,city,membership_level,cust_id,region
0,101,Maya Chen,Los Angeles,Gold,101.0,West
1,102,Jordan Smith,San Diego,Silver,102.0,West
2,103,Alex Rivera,Phoenix,Bronze,103.0,Southwest
3,104,Sofia Garcia,Los Angeles,Gold,104.0,West
4,105,Ethan Brown,Las Vegas,Silver,105.0,Southwest
5,106,Lena Patel,San Francisco,Platinum,106.0,West
6,107,Chris Johnson,Seattle,Bronze,NaN,NaN
7,108,Nora Lee,Portland,Gold,NaN,NaN

7 Merge Multiple dataframes

In order to merge multiple dataframes you can merge the dataframes step by step. This is done by using pd.merge() several times to create a master dataframe.

In [29]:
# Merge the orders_df, customer_df, 
# on the customer_od, use the left join
orders_full = pd.merge(
    orders_df,
    customers_df,
    on="customer_id",
    how="left"
)
# Merge the new dataframe with the product_df, on the product_id
orders_full = pd.merge(
    orders_full,
    products_df,
    on="product_id",
    how="left"
)
# Merge the new dataframe with the shipping_df, on the order_id
orders_full = pd.merge(
    orders_full,
    shipping_df,
    on="order_id",
    how="left"
)
# Check the dataframe
orders_full.head()

,order_id,customer_id,product_id,order_date,quantity,customer_name,city,membership_level,product_name,category,unit_price,shipping_status,shipping_cost
0,5001,101,201,2026-01-05,2,Maya Chen,Los Angeles,Gold,Laptop Stand,Office,45.0,Delivered,8.0
1,5002,102,202,2026-01-07,1,Jordan Smith,San Diego,Silver,Wireless Mouse,Electronics,25.0,Shipped,6.0
2,5003,101,203,2026-01-12,3,Maya Chen,Los Angeles,Gold,Keyboard,Electronics,70.0,Delivered,10.0
3,5004,104,201,2026-01-15,1,Sofia Garcia,Los Angeles,Gold,Laptop Stand,Office,45.0,Processing,7.0
4,5005,109,204,2026-01-18,4,NaN,NaN,NaN,Monitor,Electronics,180.0,NaN,NaN

8 Use indicator = True to check matches

Using the indicator = True adds a colums that is able to show where each row came from.

In [30]:
# Merge the orders_df and the customers_df, on the customer_id,
# use an outer join and have indicator = True
merge_check = pd.merge(
    orders_df,
    customers_df,
    on="customer_id",
    how="outer",
    indicator=True
)

# Check the dataframe
merge_check.head()

,order_id,customer_id,product_id,order_date,quantity,customer_name,city,membership_level,_merge
0,5001.0,101,201.0,2026-01-05,2.0,Maya Chen,Los Angeles,Gold,both
1,5003.0,101,203.0,2026-01-12,3.0,Maya Chen,Los Angeles,Gold,both
2,5002.0,102,202.0,2026-01-07,1.0,Jordan Smith,San Diego,Silver,both
3,5008.0,102,206.0,2026-01-25,5.0,Jordan Smith,San Diego,Silver,both
4,5006.0,103,205.0,2026-01-20,2.0,Alex Rivera,Phoenix,Bronze,both

9 Use Suffuxes for duplicate column names

There is a case where both of the dataframes have a column that will have the same name, in order to differentiate you can use suffixes for those columns when merging. This is done by using the suffixes = ("left", "right")

In [31]:
# Create these two example dataframes
customers_status_df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104],
    "status": ["Active", "Active", "Inactive", "Active"]
})

orders_status_df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104],
    "status": ["Completed", "Pending", "Completed", "Cancelled"]
})

# Merge the the two dataframes and use suffixes for the status
status_merge = pd.merge(
    orders_status_df,
    customers_status_df,
    on="customer_id",
    suffixes=("_order", "_customer")
)

# Check the dataframe 
status_merge.head()

   customer_id status_order status_customer
0          101    Completed          Active
1          102      Pending          Active
2          103    Completed        Inactive
3          104    Cancelled          Active

10 Join using .join()

The join is another way of combing two dataframe this is usually throught the index. This is done by using the function of .join()

In [32]:
# Set the index for the customers_df
customers_indexed = customers_df.set_index("customer_id")

# Create a new dataframe
membership_notes_df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "account_manager": ["Taylor", "Morgan", "Riley", "Casey",
                        "Jamie", "Drew", "Avery", "Quinn"]
}).set_index("customer_id")

# Join the customers data frame and then the new dataframe
customer_joined = customers_indexed.join(membership_notes_df)
# Check the dataframe
customer_joined.head()

            customer_name         city membership_level account_manager
customer_id
101             Maya Chen  Los Angeles             Gold          Taylor
102          Jordan Smith    San Diego           Silver          Morgan
103           Alex Rivera      Phoenix           Bronze           Riley
104          Sofia Garcia  Los Angeles             Gold           Casey
105           Ethan Brown    Las Vegas           Silver           Jamie

11 Join using indexes with left_index and right_index

Another way to use join is to use the pd.merge, but pass the arguments of left_index = True, and the right_index = True.

In [33]:
# Merge the customer_indexed, and then the membership_notes_df,
# Using the pd.merge and the indexes
customer_index_merge = pd.merge(
    customers_indexed,
    membership_notes_df,
    left_index=True,
    right_index=True
)

# Check the dataframe
customer_index_merge.head()

            customer_name         city membership_level account_manager
customer_id
101             Maya Chen  Los Angeles             Gold          Taylor
102          Jordan Smith    San Diego           Silver          Morgan
103           Alex Rivera      Phoenix           Bronze           Riley
104          Sofia Garcia  Los Angeles             Gold           Casey
105           Ethan Brown    Las Vegas           Silver           Jamie

13 Concatenating rows with pd.concat()

Concatenating refers to when you want to stack the dataframes. This is done by using the function pd.concat()

In [34]:
# Create two example dataframes
january_orders = pd.DataFrame({
    "order_id": [6001, 6002],
    "customer_id": [101, 102],
    "product_id": [201, 202],
    "quantity": [1, 2]
})

february_orders = pd.DataFrame({
    "order_id": [6003, 6004],
    "customer_id": [103, 104],
    "product_id": [203, 204],
    "quantity": [3, 1]
})

# Stack the dataframes of the two new dataframes
all_orders = pd.concat(
    [january_orders, february_orders],
    ignore_index=True
)

# Check the new dataframe
all_orders

   order_id  customer_id  product_id  quantity
0      6001          101         201         1
1      6002          102         202         2
2      6003          103         203         3
3      6004          104         204         1

14 Concaternating columns with axis = 1

This can also be done to stack them next to eachother instead of on top of eachother this is done by adding the argument of axis = 1.

In [35]:
# Create a new dataframe
customer_contact_df = pd.DataFrame({
    "email": ["maya@example.com", "jordan@example.com", "alex@example.com"],
    "phone": ["555-1111", "555-2222", "555-3333"]
})
# Create antoher dataframe
customer_basic_df = customers_df[["customer_id", "customer_name"]].head(3)
# Concatenate the two dataframe side ways
customer_side_by_side = pd.concat(
    [customer_basic_df, customer_contact_df],
    axis=1
)
# Check the dataframe
customer_side_by_side

   customer_id customer_name               email     phone
0          101     Maya Chen    maya@example.com  555-1111
1          102  Jordan Smith  jordan@example.com  555-2222
2          103   Alex Rivera    alex@example.com  555-3333