Mapping Replacing

By: Josh Navarro

Goal: Learn how to do mapping and replacing in the Jupyter Notebook and using python pandas.

Data: Created by ChatGPT

In [33]:
# Imports that we will be using
import pandas as pd
import numpy as np

In [34]:
# Create the data 
df = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115, 116],

    "employee_name": ["Maya Chen", "Jordan Smith", "Alex Rivera", "Sofia Garcia",
                      "Ethan Brown", "Lena Patel", "Chris Johnson", "Nora Lee",
                      "Daniel Kim", "Ava Wilson", "Marcus Davis", "Isabella Martinez",
                      "Noah Thompson", "Grace Nguyen", "Olivia Moore", "Elijah Brooks"],

    "department_code": ["HR", "IT", "FIN", "MKT", "IT", "HR", "OPS", "FIN",
                        "MKT", "IT", "OPS", "HR", "FIN", "MKT", "IT", "OPS"],

    "department_name": ["human resources", "Information Tech", "Finance", "marketing",
                        "IT", "Human Resources", "operations", "FINANCE",
                        "Marketing Dept", "information technology", "Ops", "HR",
                        "financial services", "MKT", "Info Tech", "Operations"],

    "employment_type": ["FT", "PT", "Contract", "Full-Time", "Part Time", "FT",
                        "contractor", "Full Time", "PT", "Part-Time", "FT",
                        "Temporary", "Contract", "full-time", "part time", "Temp"],

    "performance_rating": ["Excellent", "Good", "Average", "Poor", "Good",
                           "Excellent", "Avg", "Needs Improvement", "Poor",
                           "Good", "Excellent", "Average", "Avg", "Needs Improvement",
                           "Good", "Poor"],

    "office_location": ["LA", "Los Angeles", "L.A.", "New York", "NY",
                        "San Francisco", "SF", "S.F.", "Los Angeles", "LA",
                        "New York City", "NYC", "San Fran", "SF", "L.A.", "NY"],

    "salary_band": ["A", "B", "C", "B", "A", "C", "D", "B",
                    "C", "A", "D", "B", "C", "A", "B", "D"],

    "remote_status": ["Y", "N", "Yes", "No", "y", "n", "Remote", "Onsite",
                      "Hybrid", "H", "yes", "no", "remote", "onsite", "hybrid", "h"]
})

df

,employee_id,employee_name,department_code,department_name,employment_type,performance_rating,office_location,salary_band,remote_status
0,101,Maya Chen,HR,human resources,FT,Excellent,LA,A,Y
1,102,Jordan Smith,IT,Information Tech,PT,Good,Los Angeles,B,N
2,103,Alex Rivera,FIN,Finance,Contract,Average,L.A.,C,Yes
3,104,Sofia Garcia,MKT,marketing,Full-Time,Poor,New York,B,No
4,105,Ethan Brown,IT,IT,Part Time,Good,NY,A,y
5,106,Lena Patel,HR,Human Resources,FT,Excellent,San Francisco,C,n
6,107,Chris Johnson,OPS,operations,contractor,Avg,SF,D,Remote
7,108,Nora Lee,FIN,FINANCE,Full Time,Needs Improvement,S.F.,B,Onsite
8,109,Daniel Kim,MKT,Marketing Dept,PT,Poor,Los Angeles,C,Hybrid
9,110,Ava Wilson,IT,information technology,Part-Time,Good,LA,A,H
10,111,Marcus Davis,OPS,Ops,FT,Excellent,New York City,D,yes
11,112,Isabella Martinez,HR,HR,Temporary,Average,NYC,B,no
12,113,Noah Thompson,FIN,financial services,Contract,Avg,San Fran,C,remote
13,114,Grace Nguyen,MKT,MKT,full-time,Needs Improvement,SF,A,onsite
14,115,Olivia Moore,IT,Info Tech,part time,Good,L.A.,B,hybrid
15,116,Elijah Brooks,OPS,Operations,Temp,Poor,NY,D,h

Mapping and Replacing

Mapping refers to converting values from one form into another form. Then replacing means changing the old values into the new values.

In [35]:
# Create a copy of the dataframe
map_df = df.copy()
# Check the columns for the dataframe
map_df.columns

Index(['employee_id', 'employee_name', 'department_code', 'department_name',
       'employment_type', 'performance_rating', 'office_location',
       'salary_band', 'remote_status'],
      dtype='object')

1 Mapping values with .map()

Use the function of .map() when each old value has one matching new value. The argument that pass through the function is a dictionary.

In [36]:
# Create the dictionary
department_map = {
    "HR": "Human Resources",
    "IT": "Information Technology",
    "FIN": "Finance",
    "MKT": "Marketing",
    "OPS": "Operations"
}
# Map the dicitonary
map_df["department_full"] = map_df["department_code"].map(department_map)

# Check the dataframe
map_df.head()

,employee_id,employee_name,department_code,department_name,employment_type,performance_rating,office_location,salary_band,remote_status,department_full
0,101,Maya Chen,HR,human resources,FT,Excellent,LA,A,Y,Human Resources
1,102,Jordan Smith,IT,Information Tech,PT,Good,Los Angeles,B,N,Information Technology
2,103,Alex Rivera,FIN,Finance,Contract,Average,L.A.,C,Yes,Finance
3,104,Sofia Garcia,MKT,marketing,Full-Time,Poor,New York,B,No,Marketing
4,105,Ethan Brown,IT,IT,Part Time,Good,NY,A,y,Information Technology

2 Replacing values with .replace()

Using the .replace() function when you want to change the values inside a column. This is done by also passing a dictionary into the function.

In [37]:
# Create the dicitonary
replace = {
    "Avg" : "Average",
    "Needs Improvement": "Poor"
}

# Use the .replace() to replace the values
map_df['performance_rating'] = map_df['performance_rating'].replace(replace)

map_df.head()

,employee_id,employee_name,department_code,department_name,employment_type,performance_rating,office_location,salary_band,remote_status,department_full
0,101,Maya Chen,HR,human resources,FT,Excellent,LA,A,Y,Human Resources
1,102,Jordan Smith,IT,Information Tech,PT,Good,Los Angeles,B,N,Information Technology
2,103,Alex Rivera,FIN,Finance,Contract,Average,L.A.,C,Yes,Finance
3,104,Sofia Garcia,MKT,marketing,Full-Time,Poor,New York,B,No,Marketing
4,105,Ethan Brown,IT,IT,Part Time,Good,NY,A,y,Information Technology

3 Standardizing text before mapping

There are cases that the values would not match because there is either spacing or capitals, in order to fix you need to standardize it. You do this by using the .str.strip() and then .str.lower()

In [38]:
# Stardardize the department name column
map_df['department_name'] = map_df['department_name'].str.strip().str.lower()

# Check the dataframe 
map_df.head()

,employee_id,employee_name,department_code,department_name,employment_type,performance_rating,office_location,salary_band,remote_status,department_full
0,101,Maya Chen,HR,human resources,FT,Excellent,LA,A,Y,Human Resources
1,102,Jordan Smith,IT,information tech,PT,Good,Los Angeles,B,N,Information Technology
2,103,Alex Rivera,FIN,finance,Contract,Average,L.A.,C,Yes,Finance
3,104,Sofia Garcia,MKT,marketing,Full-Time,Poor,New York,B,No,Marketing
4,105,Ethan Brown,IT,it,Part Time,Good,NY,A,y,Information Technology

4 Mapping number from categories

Mapping number from categories is possible by using the dictionary and having the second value be a number.

In [39]:
# Create a dictionary that is able to change 
# the performance rating into numeric values
rating_score = {
    "Excellent": 4,
    "Good": 3,
    "Average": 2,
    "Poor": 1
}

# Map to the performance_rating
map_df["rating_score"] = map_df["performance_rating"].map(rating_score)

# Check the dataframe
map_df.head()

,employee_id,employee_name,department_code,department_name,employment_type,performance_rating,office_location,salary_band,remote_status,department_full,rating_score
0,101,Maya Chen,HR,human resources,FT,Excellent,LA,A,Y,Human Resources,4
1,102,Jordan Smith,IT,information tech,PT,Good,Los Angeles,B,N,Information Technology,3
2,103,Alex Rivera,FIN,finance,Contract,Average,L.A.,C,Yes,Finance,2
3,104,Sofia Garcia,MKT,marketing,Full-Time,Poor,New York,B,No,Marketing,1
4,105,Ethan Brown,IT,it,Part Time,Good,NY,A,y,Information Technology,3

5 Using .fillna() after .map()

Sometimes when you using the .map() there can create a bunch NAs in the dataframe to avoid that you can use the .fillna() function.

In [40]:
# Use the previous dictionary, to map the departments
map_df["department_full"] = (
    map_df["department_code"]
    .map(department_map)
    .fillna("Unknown")
)

# Check the dataframe
map_df.head()

,employee_id,employee_name,department_code,department_name,employment_type,performance_rating,office_location,salary_band,remote_status,department_full,rating_score
0,101,Maya Chen,HR,human resources,FT,Excellent,LA,A,Y,Human Resources,4
1,102,Jordan Smith,IT,information tech,PT,Good,Los Angeles,B,N,Information Technology,3
2,103,Alex Rivera,FIN,finance,Contract,Average,L.A.,C,Yes,Finance,2
3,104,Sofia Garcia,MKT,marketing,Full-Time,Poor,New York,B,No,Marketing,1
4,105,Ethan Brown,IT,it,Part Time,Good,NY,A,y,Information Technology,3

6 Replace partial text with .str.replace()

In order to replace part of a string, you can use the function of .str.replace(), and the pass arguments of "old_text", "new_text", and then regex=False.

In [41]:
# For the departname column replace the Dept with Department
map_df['department_name'] = map_df['department_name'].str.replace(
    "Dept",
    "Department",
    regex = False
)
# Check the dataframe
map_df.head()

,employee_id,employee_name,department_code,department_name,employment_type,performance_rating,office_location,salary_band,remote_status,department_full,rating_score
0,101,Maya Chen,HR,human resources,FT,Excellent,LA,A,Y,Human Resources,4
1,102,Jordan Smith,IT,information tech,PT,Good,Los Angeles,B,N,Information Technology,3
2,103,Alex Rivera,FIN,finance,Contract,Average,L.A.,C,Yes,Finance,2
3,104,Sofia Garcia,MKT,marketing,Full-Time,Poor,New York,B,No,Marketing,1
4,105,Ethan Brown,IT,it,Part Time,Good,NY,A,y,Information Technology,3

7 Replace values across mulitple columns

Instead of applying the replace function to only one column to can pass in more columns to apply it to many, so it uses the same .replace() but when you are filtering use a list to pass more columns.

In [42]:
# For the employment type and remote status replace key words
map_df[["employment_type", "remote_status"]] = (
    map_df[["employment_type", "remote_status"]]
    .replace({
        "Temp": "Temporary",
        "contractor": "Contract",
        "yes": "Yes",
        "no": "No"
    })
)
# Check the datafame
map_df.head()

,employee_id,employee_name,department_code,department_name,employment_type,performance_rating,office_location,salary_band,remote_status,department_full,rating_score
0,101,Maya Chen,HR,human resources,FT,Excellent,LA,A,Y,Human Resources,4
1,102,Jordan Smith,IT,information tech,PT,Good,Los Angeles,B,N,Information Technology,3
2,103,Alex Rivera,FIN,finance,Contract,Average,L.A.,C,Yes,Finance,2
3,104,Sofia Garcia,MKT,marketing,Full-Time,Poor,New York,B,No,Marketing,1
4,105,Ethan Brown,IT,it,Part Time,Good,NY,A,y,Information Technology,3

8 Using .replace() across the whole DataFrame

Instead of replacing by the specific columns you can just use the function on the whole entire dataframe instead.

In [43]:
# For the whole dataframe replace all the Y and N to yes and no
map_df = map_df.replace(
    {
        "Y" : "Yes",
        "N" : "No"
    }
)

# Check the dataframe
map_df.head()

,employee_id,employee_name,department_code,department_name,employment_type,performance_rating,office_location,salary_band,remote_status,department_full,rating_score
0,101,Maya Chen,HR,human resources,FT,Excellent,LA,A,Yes,Human Resources,4
1,102,Jordan Smith,IT,information tech,PT,Good,Los Angeles,B,No,Information Technology,3
2,103,Alex Rivera,FIN,finance,Contract,Average,L.A.,C,Yes,Finance,2
3,104,Sofia Garcia,MKT,marketing,Full-Time,Poor,New York,B,No,Marketing,1
4,105,Ethan Brown,IT,it,Part Time,Good,NY,A,y,Information Technology,3

10 Using .rename() to replace column names

In orde to repalce the columns you can use the function of .rename(), which this takes dictionary of the pre_name and then the next name

In [44]:
# Replace the column names of emnployee_id with emp_id, 
# and then employee_name with name
map_df = map_df.rename(columns={
    "employee_id": "emp_id",
    "employee_name": "name"
})
# Check the dataframe
map_df.head()

,emp_id,name,department_code,department_name,employment_type,performance_rating,office_location,salary_band,remote_status,department_full,rating_score
0,101,Maya Chen,HR,human resources,FT,Excellent,LA,A,Yes,Human Resources,4
1,102,Jordan Smith,IT,information tech,PT,Good,Los Angeles,B,No,Information Technology,3
2,103,Alex Rivera,FIN,finance,Contract,Average,L.A.,C,Yes,Finance,2
3,104,Sofia Garcia,MKT,marketing,Full-Time,Poor,New York,B,No,Marketing,1
4,105,Ethan Brown,IT,it,Part Time,Good,NY,A,y,Information Technology,3

11 Using .where() to replace values conditionally

In order to use the .where() function you pass by a condition and the replacement value, this basically keeps the value where the condition is true, and then replaces the values where the condition is false.

In [45]:
# For the salary band column check to see if the values are 
# A, B, C, D if not its unknown
map_df["salary_band_checked"] = map_df["salary_band"].where(
    map_df["salary_band"].isin(["A", "B", "C", "D"]),
    "Unknown"
)

# Check the dataframe
map_df.head()

,emp_id,name,department_code,department_name,employment_type,performance_rating,office_location,salary_band,remote_status,department_full,rating_score,salary_band_checked
0,101,Maya Chen,HR,human resources,FT,Excellent,LA,A,Yes,Human Resources,4,A
1,102,Jordan Smith,IT,information tech,PT,Good,Los Angeles,B,No,Information Technology,3,B
2,103,Alex Rivera,FIN,finance,Contract,Average,L.A.,C,Yes,Finance,2,C
3,104,Sofia Garcia,MKT,marketing,Full-Time,Poor,New York,B,No,Marketing,1,B
4,105,Ethan Brown,IT,it,Part Time,Good,NY,A,y,Information Technology,3,A

12 Using .mask() to replace values conditionally 

The .mask() function is the complete opposite of the .where() function, as it uses the condition and replacement value, but when the condition is true you replace and if the condition is false you keep.

In [46]:
# In the performance rating column find the 
# values that have poor, and replace with review

map_df["performance_rating_checked"] = map_df["performance_rating"].mask(
    map_df["performance_rating"] == "Poor",
    "Needs Review"
)

# Check the dataframe
map_df.head()

,emp_id,name,department_code,department_name,employment_type,performance_rating,office_location,salary_band,remote_status,department_full,rating_score,salary_band_checked,performance_rating_checked
0,101,Maya Chen,HR,human resources,FT,Excellent,LA,A,Yes,Human Resources,4,A,Excellent
1,102,Jordan Smith,IT,information tech,PT,Good,Los Angeles,B,No,Information Technology,3,B,Good
2,103,Alex Rivera,FIN,finance,Contract,Average,L.A.,C,Yes,Finance,2,C,Average
3,104,Sofia Garcia,MKT,marketing,Full-Time,Poor,New York,B,No,Marketing,1,B,Needs Review
4,105,Ethan Brown,IT,it,Part Time,Good,NY,A,y,Information Technology,3,A,Good